export {
  ArrowRightIcon,
  BookOpenIcon,
  FileTextIcon,
  FlagIcon,
  HomeIcon,
  ImageIcon,
  LayersIcon,
  ShieldIcon,
  TagIcon,
  UserIcon,
  UsersIcon,
  VideoIcon,
  ZapIcon,
} from '../../src/components/icons/FeatherIcons'
